/**
 * `npm run sim:support` (TODO 5.9): what the pinned gcsim implements, for
 * every character and weapon in the dataset, written to
 * `packages/engine/src/sim/gcsim-support.json` with the gcsim version it
 * was probed with. The coverage report and the "not simulated" fallback
 * read that table; a test fails when it no longer matches the pin, so it
 * is regenerated with every new gcsim.
 *
 * Each character runs alone in a one-iteration config with a Favonius
 * weapon of its type: gcsim refuses a name it doesn't know, and lists one
 * it knows only partly in `incomplete_characters`. Each weapon runs on a
 * fully implemented character of its type, and each artifact set (four
 * pieces) on a sword user: gcsim refuses an unknown one.
 *
 *   npm run sim:support
 * @packageDocumentation
 */

import { writeFileSync } from 'node:fs';
import { genshinAdapter } from '@genshin-build-lab/engine/game/genshin/adapter';
import { gcsimName } from '@genshin-build-lab/engine/sim/configgen';
import type { GcsimSupportTable } from '@genshin-build-lab/engine/sim/support';
import { ensureGcsim, GcsimError, loadGcsimTool, runGcsim } from '../sim/gcsim';
import { fromRoot } from '../paths';
import { formatJson } from '../sim/rotations';

const OUT = fromRoot('packages/engine/src/sim/gcsim-support.json');
const CONCURRENCY = 8;

/** A weapon of each type that every gcsim implements. */
const PROBE_WEAPON: Record<string, string> = {
  sword: 'favonius_sword',
  claymore: 'favonius_greatsword',
  polearm: 'favonius_lance',
  bow: 'favonius_warbow',
  catalyst: 'favonius_codex',
};

const config = (character: string, weapon: string, set?: string) =>
  [
    'options iteration=1 swap_delay=12;',
    'target lvl=100 resist=0.1 hp=999999999;',
    'energy every interval=480,720 amount=1;',
    `${gcsimName(character)} char lvl=90/90 cons=0 talent=1,1,1;`,
    `${gcsimName(character)} add weapon="${gcsimName(weapon)}" refine=1 lvl=90/90;`,
    ...(set
      ? [`${gcsimName(character)} add set="${gcsimName(set)}" count=4;`]
      : []),
    `active ${gcsimName(character)};`,
    `${gcsimName(character)} attack;`,
    '',
  ].join('\n');

/** Run `jobs` at most `CONCURRENCY` at a time. */
async function inParallel<T>(jobs: (() => Promise<T>)[]): Promise<T[]> {
  const out: T[] = new Array(jobs.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (next < jobs.length) {
        const i = next++;
        out[i] = await jobs[i]();
      }
    }),
  );
  return out;
}

const tool = loadGcsimTool();
const { path } = await ensureGcsim(tool, { log: (l) => console.log(l) });
const probe = async (character: string, weapon: string, set?: string) => {
  try {
    const r = (await runGcsim(path, config(character, weapon, set), {
      timeoutMs: 60_000,
    })) as { incomplete_characters?: string[] };
    return r.incomplete_characters?.length ? 'partial' : 'ok';
  } catch (e) {
    if (e instanceof GcsimError) return 'refused';
    throw e;
  }
};

const characters = genshinAdapter.characters();
const charResults = await inParallel(
  characters.map(
    (c) => () => probe(c.key, PROBE_WEAPON[c.weaponType] ?? 'favonius_sword'),
  ),
);
const charSupport = Object.fromEntries(
  characters.map((c, i) => [
    c.key,
    charResults[i] === 'ok'
      ? 'full'
      : charResults[i] === 'partial'
        ? 'partial'
        : 'unsupported',
  ]),
) as GcsimSupportTable['characters'];

/** A fully implemented character of each weapon type, to carry weapons. */
const carrier = Object.fromEntries(
  Object.keys(PROBE_WEAPON).map((type) => [
    type,
    characters.find(
      (c) => c.weaponType === type && charSupport[c.key] === 'full',
    )?.key,
  ]),
);
const weapons = genshinAdapter.weapons();
const weaponResults = await inParallel(
  weapons.map((w) => () => {
    const who = carrier[w.type];
    if (!who)
      throw new Error(`no implemented ${w.type} user to carry ${w.key}`);
    return probe(who, w.key);
  }),
);
const sets = genshinAdapter.sets();
const setResults = await inParallel(
  sets.map((s) => () => probe(carrier.sword!, PROBE_WEAPON.sword, s.key)),
);
const table: GcsimSupportTable = {
  about:
    'Generated by npm run sim:support: what the pinned gcsim implements, per dataset character, weapon and artifact set. Regenerate after a new gcsim pin.',
  gcsim: tool.version,
  commit: tool.commit,
  characters: charSupport,
  weapons: Object.fromEntries(
    weapons.map((w, i) => [
      w.key,
      weaponResults[i] === 'refused' ? 'unsupported' : 'supported',
    ]),
  ) as GcsimSupportTable['weapons'],
  sets: Object.fromEntries(
    sets.map((x, i) => [
      x.key,
      setResults[i] === 'refused' ? 'unsupported' : 'supported',
    ]),
  ) as GcsimSupportTable['sets'],
};
writeFileSync(OUT, formatJson(table));

const list = (o: Record<string, string>, v: string) =>
  Object.keys(o).filter((k) => o[k] === v);
console.log(
  `gcsim ${tool.version}: characters ${list(table.characters, 'full').length} full, ${list(table.characters, 'partial').length} partial (${list(table.characters, 'partial').join(', ') || 'none'}), ${list(table.characters, 'unsupported').length} not implemented (${list(table.characters, 'unsupported').join(', ') || 'none'}).`,
);
console.log(
  `weapons ${list(table.weapons, 'supported').length} implemented, ${list(table.weapons, 'unsupported').length} not (${list(table.weapons, 'unsupported').join(', ') || 'none'}).`,
);
console.log(
  `sets ${list(table.sets, 'supported').length} implemented, ${list(table.sets, 'unsupported').length} not (${list(table.sets, 'unsupported').join(', ') || 'none'}).`,
);
console.log(`written to ${OUT}`);
